# Generated by Django 2.1.7 on 2019-03-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='invEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=21)),
                ('employee', models.IntegerField(default=0)),
                ('beginv', models.IntegerField(default=0)),
                ('endinv', models.IntegerField(default=0)),
                ('delivery', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('salesamount', models.FloatField(default=0)),
                ('shortage', models.IntegerField(default=0)),
                ('shortageamount', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
        migrations.CreateModel(
            name='invItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=21)),
                ('price', models.FloatField(default=0)),
                ('inv', models.IntegerField(default=0)),
            ],
        ),
    ]
