# Generated by Django 2.1.7 on 2019-03-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventry',
            name='actualinv',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='shortage',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='shortageamount',
            field=models.FloatField(default=None),
        ),
    ]
